apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hrms-db
  labels: # these lables are deployment lables
    name: hrms
    tier: db
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hrms
      tier: db
      env: dev
  serviceName: <ServiceName>
  template:
    metadata:
      labels:
        name: hrms
        tier: db
        env: dev
    spec:
      containers:
      - name: hrms_db
        image: postgres:12
        ports:
        - containerPort: 5432
          name: hrms-db-port
        volumeMounts:
        - name: hrms-db-vc
          mountPath: /var/lib/postgresql
        envFrom:
          - secretRef:
              name: hrms-db-secret

  volumeClaimTemplates:
  - metadata:
      name: hrms-db-vc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
      storageClassName: "ebs-sc"
---
apiVersion: v1
kind: Service
metadata:
  name: hrms-db-service
spec:
  selector:
    name: hrms-web
    tier: app
    env: dev
  ports:
  - port: 5432 
    targetPort: hrms-db-port
---
apiVersion: v1
kind: Secret
metadata:
  name: hrms-db-secret
type: Opaque
data:
  POSTGRES_DB: TmV3U2VydmVycnJycnI=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: dXV1dTExMTE=

