apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms-api
  labels: # deployment lables
    name: hrms
    tier: api
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels: #these lables are used to find pod lables. these should match with pod lables.
      name: hrms
      tier: api
      env: dev 
  template:
    metadata:
      labels: # pod lables
        name: hrms
        tier: api
        env: dev 
    spec:
      containers:
      - name: hrms-api
        image: ashokdock/hrms_api:v1
        imagePullPolicy: Always
        resources:
          request:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /api/
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: hrms-api-config
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hrms-api-config
data:
  DATABASE_HOST: service-name of db
  DATABASE_PORT: "5432"
  DATABASE_NAME: NewServerrrrrr
  DATABASE_USER: postgres
  DATABASE_PASSWORD: uuuu1111
  EMAIL_HOST_PASSWORD: 72A1E73834FF483792ED9D18912D7E32BB85
  EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
  EMAIL_HOST: smtp.elasticemail.com
  EMAIL_PORT: "2525"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "False"
  DEFAULT_FROM_EMAIL: hrms.marolix@gmail.com
  EMAIL_HOST_USER: hrms.marolix@gmail.com
---
apiVersion: v1
kind: Service
metadata:
  name: hrms-api-service
spec:
  type: NodePort
  selector:
    name: hrms
    tier: api
    env: dev
  ports:
  - port: 8000
    targetPort: 8000
